import { DrawerMethod } from './drawer';
// @ts-nocheck
import { MessageMethod } from './message';
import { ModalMethod } from './modal';
import { NotificationMethod } from './notification';

type SDVue = typeof import('./index');

declare module 'vue' {
  export interface GlobalComponents {
    SdAffix: SDVue['Affix'];
    SdAlert: SDVue['Alert'];
    SdAnchor: SDVue['Anchor'];
    SdAnchorLink: SDVue['AnchorLink'];
    SdAutoComplete: SDVue['AutoComplete'];
    SdAvatar: SDVue['Avatar'];
    SdAvatarGroup: SDVue['AvatarGroup'];
    SdBackTop: SDVue['BackTop'];
    SdBadge: SDVue['Badge'];
    SdBreadcrumb: SDVue['Breadcrumb'];
    SdBreadcrumbItem: SDVue['BreadcrumbItem'];
    SdButton: SDVue['Button'];
    SdButtonGroup: SDVue['ButtonGroup'];
    SdCalendar: SDVue['Calendar'];
    SdCard: SDVue['Card'];
    SdCardMeta: SDVue['CardMeta'];
    SdCardGrid: SDVue['CardGrid'];
    SdCarousel: SDVue['Carousel'];
    SdCarouselItem: SDVue['CarouselItem'];
    SdCascader: SDVue['Cascader'];
    SdCascaderPanel: SDVue['CascaderPanel'];
    SdCheckbox: SDVue['Checkbox'];
    SdCheckboxGroup: SDVue['CheckboxGroup'];
    SdCollapse: SDVue['Collapse'];
    SdCollapseItem: SDVue['CollapseItem'];
    SdColorPicker: SDVue['ColorPicker'];
    SdComment: SDVue['Comment'];
    SdConfigProvider: SDVue['ConfigProvider'];
    SdCopy: SDVue['Copy'];
    SdCropper: SDVue['Cropper'];
    SdDatePicker: SDVue['DatePicker'];
    SdWeekPicker: SDVue['WeekPicker'];
    SdMonthPicker: SDVue['MonthPicker'];
    SdYearPicker: SDVue['YearPicker'];
    SdQuarterPicker: SDVue['QuarterPicker'];
    SdRangePicker: SDVue['RangePicker'];
    SdDescriptions: SDVue['Descriptions'];
    SdDescriptionsItem: SDVue['DescriptionsItem'];
    SdDivider: SDVue['Divider'];
    SdDrawer: SDVue['Drawer'];
    SdDropdown: SDVue['Dropdown'];
    SdDoption: SDVue['Doption'];
    SdDgroup: SDVue['Dgroup'];
    SdDsubmenu: SDVue['Dsubmenu'];
    SdEllipsis: SDVue['Ellipsis'];
    SdPerformantEllipsis: SDVue['PerformantEllipsis'];
    SdEmpty: SDVue['Empty'];
    SdForm: SDVue['Form'];
    SdFormItem: SDVue['FormItem'];
    SdGrid: SDVue['Grid'];
    SdGridItem: SDVue['GridItem'];
    SdCol: SDVue['Col'];
    SdRow: SDVue['Row'];
    SdImage: SDVue['Image'];
    SdImagePreview: SDVue['ImagePreview'];
    SdImagePreviewAction: SDVue['ImagePreviewAction'];
    SdImagePreviewGroup: SDVue['ImagePreviewGroup'];
    SdInput: SDVue['Input'];
    SdInputGroup: SDVue['InputGroup'];
    SdInputSearch: SDVue['InputSearch'];
    SdInputPassword: SDVue['InputPassword'];
    SdInputNumber: SDVue['InputNumber'];
    SdInputTag: SDVue['InputTag'];
    SdLayout: SDVue['Layout'];
    SdLayoutHeader: SDVue['LayoutHeader'];
    SdLayoutContent: SDVue['LayoutContent'];
    SdLayoutFooter: SDVue['LayoutFooter'];
    SdLayoutSider: SDVue['LayoutSider'];
    SdLink: SDVue['Link'];
    SdList: SDVue['List'];
    SdListItem: SDVue['ListItem'];
    SdListItemMeta: SDVue['ListItemMeta'];
    SdMention: SDVue['Mention'];
    SdMenu: SDVue['Menu'];
    SdMenuItem: SDVue['MenuItem'];
    SdMenuItemGroup: SDVue['MenuItemGroup'];
    SdSubMenu: SDVue['SubMenu'];
    SdModal: SDVue['Modal'];
    SdPageHeader: SDVue['PageHeader'];
    SdPagination: SDVue['Pagination'];
    SdPopconfirm: SDVue['Popconfirm'];
    SdPopover: SDVue['Popover'];
    SdProgress: SDVue['Progress'];
    SdRadio: SDVue['Radio'];
    SdRadioGroup: SDVue['RadioGroup'];
    SdRate: SDVue['Rate'];
    SdResizeBox: SDVue['ResizeBox'];
    SdResult: SDVue['Result'];
    SdSelect: SDVue['Select'];
    SdSecret: SDVue['Secret'];
    SdOption: SDVue['Option'];
    SdOptgroup: SDVue['Optgroup'];
    SdSkeleton: SDVue['Skeleton'];
    SdSkeletonLine: SDVue['SkeletonLine'];
    SdSkeletonShape: SDVue['SkeletonShape'];
    SdSlider: SDVue['Slider'];
    SdSpace: SDVue['Space'];
    SdSpin: SDVue['Spin'];
    SdSplit: SDVue['Split'];
    SdStatistic: SDVue['Statistic'];
    SdCountdown: SDVue['Countdown'];
    SdSteps: SDVue['Steps'];
    SdStep: SDVue['Step'];
    SdSwitch: SDVue['Switch'];
    SdTable: SDVue['Table'];
    SdThead: SDVue['Thead'];
    SdTd: SDVue['Td'];
    SdTh: SDVue['Th'];
    SdTr: SDVue['Tr'];
    SdTbody: SDVue['Tbody'];
    SdTableColumn: SDVue['TableColumn'];
    SdTabs: SDVue['Tabs'];
    SdTabPane: SDVue['TabPane'];
    SdTag: SDVue['Tag'];
    SdTextarea: SDVue['Textarea'];
    SdTimePicker: SDVue['TimePicker'];
    SdTimeline: SDVue['Timeline'];
    SdTimelineItem: SDVue['TimelineItem'];
    SdTooltip: SDVue['Tooltip'];
    SdTransfer: SDVue['Transfer'];
    SdTree: SDVue['Tree'];
    SdTreeSelect: SDVue['TreeSelect'];
    SdTrigger: SDVue['Trigger'];
    SdTypography: SDVue['Typography'];
    SdTypographyParagraph: SDVue['TypographyParagraph'];
    SdTypographyTitle: SDVue['TypographyTitle'];
    SdTypographyText: SDVue['TypographyText'];
    SdUpload: SDVue['Upload'];
    SdVerificationCode: SDVue['VerificationCode'];
    SdWatermark: SDVue['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
