export default [
  {
    name: 'common',
    list: ['button', 'icon', 'link', 'typography'],
  },
  {
    name: 'layout',
    list: ['divider', 'grid', 'layout', 'space'],
  },
  {
    name: 'dataDisplay',
    list: [
      'avatar',
      'badge',
      'card',
      'carousel',
      'collapse',
      'comment',
      'descriptions',
      'empty',
      'image',
      'list',
      'popover',
      'statistic',
      'table',
      'tabs',
      'tag',
      'timeline',
      'tooltip',
      'tree',
    ],
  },
  {
    name: 'dataEntry',
    list: [
      'autoComplete',
      'cascader',
      'checkbox',
      'datePicker',
      'form',
      'input',
      'inputNumber',
      'mentions',
      'radio',
      'rate',
      'select',
      'slider',
      'switch',
      'timePicker',
      'transfer',
      'treeSelect',
      'upload',
    ],
  },
  {
    name: 'feedback',
    list: [
      'alert',
      'drawer',
      'message',
      'modal',
      'notification',
      'popconfirm',
      'progress',
      'result',
      'spin',
      'skeleton',
    ],
  },
  {
    name: 'navigation',
    list: [
      'breadcrumb',
      'dropdown',
      'menu',
      'pageHeader',
      'pagination',
      'steps',
    ],
  },
  {
    name: 'other',
    list: [
      'affix',
      'anchor',
      'backTop',
      'configProvider',
      'resizeBox',
      'trigger',
    ],
  },
];
