import '../../style/index.less';
import '../../checkbox/style';
import '../../button/style';
import '../../empty/style';
import '../../pagination/style';
import '../../radio/style';
import '../../spin/style';
import '../../trigger/style';
import './index.less';
