name: deploy-site-preview
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  deploy-preview:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: npm i lerna -g && yarn

      - name: build components
        run: npm run init

      - name: build site
        run: NODE_OPTIONS=--max-old-space-size=8192 AssetsPublicPath=/ yarn build:site

      - name: netlify install
        run: yarn add netlify-cli -D

      - name: get PreviewID
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "PreviewID=${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "PreviewID=main" >> $GITHUB_ENV
          fi

      - name: netlify deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID  --dir=dist --alias=pr-preview-${{ env.PreviewID }}

  add-pr-comment:
    runs-on: ubuntu-latest
    needs: deploy-preview
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: PR Comment
        uses: mshick/add-pr-comment@v2
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          # GITHUB_TOKEN secret
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: pr-${{ env.PR_NUMBER }}
          # Message to comment
          message: |
            [📚 📚 Site Preview: https://pr-preview-${{ env.PR_NUMBER }}--arco-design-vue.netlify.app](https://pr-preview-${{ env.PR_NUMBER }}--arco-design-vue.netlify.app)

  image-test:
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: install
        run: yarn

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: build:cjs
        run: yarn icon && yarn build:cjs

      - name: get PreviewID
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "PreviewID=${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "PreviewID=main" >> $GITHUB_ENV
          fi

      - name: gen screenshots
        run: yarn run test:screenshots --domain=https://pr-preview-${{ env.PreviewID }}--arco-design-vue.netlify.app

      - name: upload screenshots to argos-cli
        run: npx @argos-ci/cli upload ./tests/__screenshots__
